-- Celebal Summer Internship 2026
-- Week 3: Superstore Database
-- Author: Manjit Bajaj

-- use superstore database
USE superstore_db;

show tables;
-- Result: superstore_raw

-- Create customer table
CREATE TABLE customers (
    customer_id VARCHAR(50) PRIMARY KEY,
    customer_name VARCHAR(100),
    segment VARCHAR(50)
);

-- Create Products table
CREATE TABLE products (
    product_id VARCHAR(50) PRIMARY KEY,
    product_name VARCHAR(255),
    category VARCHAR(100),
    sub_category VARCHAR(100)
);

-- Create orders table
CREATE TABLE orders (
    row_id INT PRIMARY KEY,
    order_id VARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    product_id VARCHAR(50),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,2),
    state VARCHAR(100),
    city VARCHAR(100),
    region VARCHAR(50)
);

-- Insert records in the table
INSERT INTO customers (customer_id, customer_name, segment)
SELECT DISTINCT `Customer ID`, `Customer Name`,Segment
FROM superstore_raw;

INSERT INTO products (product_id, product_name, category, sub_category)
SELECT `Product ID`, MAX(`Product Name`), MAX(Category), MAX(`Sub-Category`)
FROM superstore_raw
GROUP BY `Product ID`;

INSERT INTO orders (row_id, order_id, order_date, ship_date, ship_mode, customer_id, product_id, sales, quantity, discount, profit, state, city, region)
SELECT `Row ID`,`Order ID`, STR_TO_DATE(`Order Date`, '%m/%d/%Y'), STR_TO_DATE(`Ship Date`, '%m/%d/%Y'), `Ship Mode`, `Customer ID`,
    `Product ID`, ROUND(Sales, 2), Quantity, ROUND(Discount, 2), ROUND(Profit, 2), State, City, Region
FROM superstore_raw;

-- 1. Find all orders where sales are greater than the average sales
SELECT * FROM orders WHERE
sales > (SELECT AVG(sales) FROM Orders);
/*
Insight: Identifies high-value orders that perform better than the overall average sales.
These orders can help understand premium purchases and major revenue contributors.
*/

-- 2. Find the highest sales order for each customer
SELECT * FROM orders o WHERE
sales = (SELECT MAX(sales) FROM orders
		WHERE customer_id = o.customer_id);
/*
Insight: retrives each customer's most valuable purchase.
*/
        
-- 3. Calculate total sales for each customer.
WITH customer_sales AS
(
SELECT customer_id, sum(sales) as total_sales FROM orders GROUP BY customer_id
)
SELECT * FROM customer_sales;
/*
Insight: Calculates the total sales generated by every customer.
This forms the foundation for customer segmentation and ranking analysis.
*/

-- 4.Find customers whose total sales are above average.
WITH customer_sales as (
SELECT customer_id, sum(sales) as total_sales FROM orders GROUP BY customer_id
)
SELECT * FROM customer_sales WHERE total_sales > 
( SELECT avg(total_sales) FROM customer_sales);
/*
Insight: Identifies customers whose overall purchases exceed the average customer sales.
These customers represent high-value customers and can be targeted for loyalty programs.
*/

-- 5. Rank all customers based on total sales.
WITH customer_sales as
( SELECT customer_id, sum(sales) as total_sales FROM orders GROUP BY customer_id)
SELECT * , RANK() OVER(ORDER BY total_sales DESC) AS sales_rank
FROM customer_sales;
/*
Insight:  Assigns a sales rank to every customer according to total revenue generated.
Helps identify top-performing customers for business analysis and decision-making.
*/

-- 6. Assign row numbers to each order within a customer.
SELECT order_id, customer_id, sales, ROW_NUMBER() OVER(
PARTITION BY customer_id ORDER BY sales DESC) as row_no FROM orders;
/*
Insight: Numbers every order for each customer based on sales value.
Useful for identifying the highest, second-highest, and subsequent orders of each customer.
*/

-- 7. Display top 3 customers based on total sales. 
WITH customer_sales as (SELECT customer_id, sum(sales) as total_sales
FROM orders GROUP BY customer_id),
Ranking as ( SELECT *, RANK() OVER(ORDER BY total_sales DESC) ranking FROM customer_sales)
Select * FROM ranking WHERE ranking<=3;
/*
Insight: Displays the three highest revenue-generating customers.
These customers contribute significantly to overall sales and are valuable for retention strategies.
*/

-- Final combined query
with customer_sales as (
SELECT customer_id, sum(sales) as total_sales FROM orders GROUP BY customer_id)

SELECT c.customer_name, cs.total_sales, RANK() OVER(ORDER BY cs.total_sales desc) as sales_rank
FROM customer_sales cs
JOIN customers c
ON cs.customer_id = c.customer_id ORDER BY sales_rank;
/*
Insight: Combines JOIN, CTE, and Window Functions to generate a ranked customer sales report.
Provides customer names, total sales, and rankings in a single business-ready output.
*/






